version: '3.1'
services:
  app-sinarodo:
    image: guisevero/apisinarodo:1.0.0
    ports:
      - "8080:8080"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.production
      - ALLOWED_HOSTS=localhost,127.0.0.1,severo.tech,app-sinarodo
