# Generated by Django 2.1.3 on 2018-12-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, unique=True)),
                ('peso', models.IntegerField()),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acrescimo_encarregado', models.FloatField(blank=True, default=10.0)),
                ('dias_em_campo', models.IntegerField(blank=True, default=15)),
                ('premio_seis', models.FloatField(blank=True, default=200.0)),
                ('premio_sete', models.FloatField(blank=True, default=400.0)),
                ('premio_oito', models.FloatField(blank=True, default=600.0)),
                ('premio_nove', models.FloatField(blank=True, default=800.0)),
                ('premio_dez', models.FloatField(blank=True, default=1000.0)),
            ],
            options={
                'db_table': 'configuracoes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=20, unique=True)),
                ('data_lancamento', models.DateField()),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'obras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ObrasUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.FloatField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('encarregado', models.BooleanField(blank=True, default=False)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_obra', to='api.Obras')),
            ],
            options={
                'db_table': 'obrasusuarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Premiacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_periodo', models.IntegerField()),
                ('ano_periodo', models.IntegerField()),
                ('dias_em_campo', models.IntegerField()),
                ('nota', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Categorias')),
                ('obras_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiacoes', to='api.ObrasUsuarios')),
            ],
            options={
                'db_table': 'premiacoes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(blank=True, null=True, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(blank=True, max_length=60, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('precisa_novo_password', models.BooleanField(blank=True, default=True)),
                ('permissao', models.IntegerField(blank=True, default=3)),
                ('funcao_1', models.CharField(blank=True, max_length=30, null=True)),
                ('funcao_2', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='obrasusuarios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Usuarios'),
        ),
        migrations.AlterUniqueTogether(
            name='premiacoes',
            unique_together={('mes_periodo', 'ano_periodo', 'categoria', 'obras_usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='obrasusuarios',
            unique_together={('obra', 'usuario')},
        ),
    ]
