# Generated by Django 2.1.3 on 2018-11-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasusuarios',
            name='encarregado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='premiacoes',
            name='obras_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiacoes', to='api.ObrasUsuarios'),
        ),
    ]
