# Generated by Django 2.1.3 on 2018-12-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracoes',
            name='valor_por_ponto',
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='dias_em_campo',
            field=models.IntegerField(blank=True, default=15),
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='premio_dez',
            field=models.FloatField(blank=True, default=1000.0),
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='premio_nove',
            field=models.FloatField(blank=True, default=800.0),
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='premio_oito',
            field=models.FloatField(blank=True, default=600.0),
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='premio_seis',
            field=models.FloatField(blank=True, default=200.0),
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='premio_sete',
            field=models.FloatField(blank=True, default=400.0),
        ),
        migrations.AlterField(
            model_name='configuracoes',
            name='acrescimo_encarregado',
            field=models.FloatField(blank=True, default=10.0),
        ),
    ]
