# Generated by Django 2.1.3 on 2018-11-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiacoes',
            name='obras_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.ObrasUsuarios'),
            preserve_default=False,
        ),
    ]
