# Generated by Django 2.1.5 on 2019-06-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_logs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='obrasusuarios',
            unique_together=set(),
        ),
    ]
