# Generated by Django 2.1.5 on 2019-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190616_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasusuarios',
            name='data_final',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='obrasusuarios',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
    ]
